# custom
custom:
  configserver:
    host: http://localhost:8071

server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cards_db
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
  config:
    import: configserver:${custom.configserver.host}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
