server:
  port: 8072

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: accounts_route
              uri: lb://ACCOUNTS
              predicates:
                - Path=/eazybank/accounts/**
              filters:
                - RewritePath=/eazybank/accounts/?(?<segment>.*), /$\{segment}
                - name: CircuitBreaker
                  args:
                    name: accountsCircuitBreaker
                    fallbackUri: forward:/fallback
            - id: loans_route
              uri: lb://LOANS
              predicates:
                - Path=/eazybank/loans/**
              filters:
                - RewritePath=/eazybank/loans/?(?<segment>.*), /$\{segment}
            - id: cards_route
              uri: lb://CARDS
              predicates:
                - Path=/eazybank/cards/**
              filters:
                - RewritePath=/eazybank/cards/?(?<segment>.*), /$\{segment}

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-type: COUNT_BASED
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 5
      failure-rate-threshold: 50 # percentage
      wait-duration-in-open-state: 10000 # milliseconds
      max-wait-duration-in-half-open-state: 10000 # milliseconds


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: UNRESTRICTED
  info:
    env:
      enabled: true

info:
  app:
    name: API Gateway
    description: API Gateway for EazyBank microservices
    version: 1.0.0