name: EazyBank microservices
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - eazybank-backend
    deploy:
      resources:
        limits:
          memory: 500mb

  config-server:
    image: ysfkhan/eazybank-configserver:v1
    container_name: config-server
    ports:
      - "8071:8071"
    healthcheck:
      # "jq" tool needs to be installed in the container for this command to work
#      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | jq -e '.status == \"UP\"' > /dev/null"
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - eazybank-backend
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 500mb

  accounts-service:
    image: ysfkhan/eazybank-accounts-ms:v1
    container_name: accounts-service
    ports:
      - "8080:8080"
    networks:
      - eazybank-backend
    environment:
      # spring.config.import cannot be overridden from the docker-compose file.
      # so alternate approach is used to achieve the same result.
#      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - CUSTOM_CONFIGSERVER_HOST=http://config-server:8071
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 500mb

  cards-service:
    image: ysfkhan/eazybank-cards-ms:v1
    container_name: cards-service
    ports:
      - "9000:9000"
    networks:
      - eazybank-backend
    environment:
#      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - CUSTOM_CONFIGSERVER_HOST=http://config-server:8071
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 500mb

  loans-service:
    image: ysfkhan/eazybank-loans-ms:v1
    container_name: loans-service
    ports:
      - "8090:8090"
    networks:
      - eazybank-backend
    environment:
#      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - CUSTOM_CONFIGSERVER_HOST=http://config-server:8071
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 500mb

networks:
  eazybank-backend:
    driver: bridge

